### ISSUE TITLE
[BUG] 新插件下载失败或依赖安装失败时不能再用指令更新插件

### ISSUE THREAD

**Issue by Glucy-2** [Ivan-1F/MCDReforgedPluginManager#2]
新插件下载失败或依赖安装失败时不能再用指令更新插件

建议：
先下载新插件（到临时目录）并安装依赖，下载完成后再删除旧插件安装新插件

日志：
```py
!!mpm upgrade timed_quick_backup_multi
[MCDR] [17:06:26] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi 有新版本可用: 1.2.0
[MCDR] [17:06:26] [TaskExecutor/INFO]: 更新操作确认:
[MCDR] [17:06:26] [TaskExecutor/INFO]: 将安装或更新以下插件:
[MCDR] [17:06:26] [TaskExecutor/INFO]: timed_quick_backup_multi
[MCDR] [17:06:26] [TaskExecutor/INFO]: 请使用 !!mpm confirm 确认操作
!!mpm confirm
[MCDR] [17:06:28] [mpm-installer/INFO]: 正在 更新 timed_quick_backup_multi
[MCDR] [17:06:28] [mpm-installer/INFO]:   正在删除 plugins/TimedQBM-v1.1.0.mcdr
[MCDR] [17:06:32] [mpm-installer/INFO]:   正在下载 TimedQBM-v1.2.0.mcdr
[MCDR] [17:06:37] [mpm-installer/INFO]:     发生异常: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)
[MCDR] [17:06:37] [mpm-installer/INFO]: 操作失败
[MCDR] [17:07:01] [mpm-cache/INFO] [mcdreforged_plugin_manager]: 正在更新插件库索引
[MCDR] [17:07:01] [CacheClock/INFO] [mcdreforged_plugin_manager]: 以下插件需要更新:
[MCDR] [17:07:01] [CacheClock/INFO] [mcdreforged_plugin_manager]: Timed QBM (timed_quick_backup_multi)
[MCDR] [17:07:01] [CacheClock/INFO] [mcdreforged_plugin_manager]: 1.1.0 -> 1.2.0 [↑]
[MCDR] [17:07:05] [mpm-cache/INFO] [mcdreforged_plugin_manager]: 插件库索引更新完成; 新增 0 个插件
!!mpm upgrade timed_quick_backup_multi
[MCDR] [17:07:19] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi 有新版本可用: 1.2.0
[MCDR] [17:07:19] [TaskExecutor/INFO]: 更新操作确认:
[MCDR] [17:07:19] [TaskExecutor/INFO]: 将安装或更新以下插件:
[MCDR] [17:07:19] [TaskExecutor/INFO]: timed_quick_backup_multi
[MCDR] [17:07:19] [TaskExecutor/INFO]: 请使用 !!mpm confirm 确认操作
!!mpm confirm
[MCDR] [17:07:24] [mpm-installer/INFO]: 正在 更新 timed_quick_backup_multi
[MCDR] [17:07:24] [mpm-installer/INFO]:   正在删除 plugins/TimedQBM-v1.1.0.mcdr
Exception in thread mpm-installer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/operation/installer.py", line 217, in run
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/operation/installer.py", line 48, in operate
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/util/mcdr_util.py", line 15, in remove_plugin_file
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/TimedQBM-v1.1.0.mcdr'
[MCDR] [17:34:14] [mpm-installer/INFO]: 正在 更新 chatbridge
[MCDR] [17:34:14] [mpm-installer/INFO]:   正在删除 plugins/ChatBridge.pyz
[MCDR] [17:34:18] [mpm-installer/INFO]:   正在下载 ChatBridge.pyz
[MCDR] [17:34:28] [mpm-installer/INFO]:     发生异常: HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=10)
[MCDR] [17:34:28] [mpm-installer/INFO]: 正在 安装 pycryptodome
[MCDR] [17:34:28] [mpm-installer/INFO]:   正在通过 pip 安装 pycryptodome
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.10/dist-packages (3.15.0)
[MCDR] [17:34:31] [mpm-installer/INFO]: 正在 安装 colorlog
[MCDR] [17:34:31] [mpm-installer/INFO]:   正在通过 pip 安装 colorlog
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (6.6.0)
[MCDR] [17:34:32] [mpm-installer/INFO]: 操作失败
[MCDR] [17:38:47] [TaskExecutor/INFO]: 插件 chatbridge 有新版本可用: 2.3.0
[MCDR] [17:38:47] [TaskExecutor/INFO]: 更新操作确认:
[MCDR] [17:38:47] [TaskExecutor/INFO]: 将安装或更新以下插件:
[MCDR] [17:38:47] [TaskExecutor/INFO]: chatbridge
[MCDR] [17:38:47] [TaskExecutor/INFO]: 将安装或更新以下包:
[MCDR] [17:38:47] [TaskExecutor/INFO]: pycryptodome, colorlog
[MCDR] [17:38:47] [TaskExecutor/INFO]: 请使用 !!mpm confirm 确认操作
[MCDR] [17:38:48] [mpm-installer/INFO]: 正在 更新 chatbridge
[MCDR] [17:38:48] [mpm-installer/INFO]:   正在删除 plugins/ChatBridge.pyz
Exception in thread mpm-installer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/operation/installer.py", line 217, in run
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/operation/installer.py", line 48, in operate
  File "plugins/MCDReforgedPluginManager-v1.3.1.mcdr/mcdreforged_plugin_manager/util/mcdr_util.py", line 15, in remove_plugin_file
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/ChatBridge.pyz'
```

**Comment by Ivan-1F** [comment]
试试这个 https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/4171483713

**Comment by Ivan-1F** [comment]
已发布 [v1.3.2](https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/tag/v1.3.2)
