### ISSUE TITLE
使用mpm之后出现错误，无法正常运行

### ISSUE THREAD

**Issue by BakaReimu** [Ivan-1F/MCDReforgedPluginManager#4]
报错日志：
> !!mpm list
[MCDR] [21:50:43] [TaskExecutor/ERROR]: Error when executing command "!!mpm list" with command source "Console" on Lite2
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\command\command_manager.py", line 70, in _traverse
    node.execute(source, command)
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 453, in execute
    self._execute_command(context)
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 362, in _executed
    child_literal._execute_command(context)
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 341, in _executed
    self.__smart_callback(callback, context.source, context)
  File "C:\Program Files\Python311\Lib\site-packages\mcdreforged\command\builder\nodes\basic.py", line 291, in __smart_k
    return callback(*args[:spec_args_len])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\MCDReforgedPluginManager-v1.3.2.mcdr\mcdreforged_plugin_manager\entries\mcdr_entry.py", line 22, in <la>
    .runs(lambda src: list_plugins(src))
                      ^^^^^^^^^^^^^^^^^
  File "plugins\MCDReforgedPluginManager-v1.3.2.mcdr\mcdreforged_plugin_manager\commands.py", line 66, in list_plugins
    for plugin in cache.get_plugins_by_labels(labels):
  File "plugins\MCDReforgedPluginManager-v1.3.2.mcdr\mcdreforged_plugin_manager\storage\plugin.py", line 202, in get_pls
    if any([label in labels for label in plugin.labels]):
                                         ^^^^^^^^^^^^^
AttributeError: 'MetaInfo' object has no attribute 'labels'

**Comment by Ivan-1F** [comment]
PluginCatalogue 近期移除了 mpm 依赖的 https://raw.githubusercontent.com/MCDReforged/PluginCatalogue/meta/plugins.json 文件中每个插件的 `labels` 字段，这导致目前无法使用先前的方式获取插件的标签

鉴于 PluginCatalogue 并没有重新添加 `labels` 字段的计划（[PuginCatalogue#262](https://github.com/MCDReforged/PluginCatalogue/issues/262)），可能需要重写插件拉取逻辑

**Comment by Ivan-1F** [comment]
PluginCatalogue 在 `plugins.json` 中追加了包含 `labels` 的 `plugin_info` 字段：https://github.com/MCDReforged/PluginCatalogue/issues/262#issuecomment-1492915917

MCDReforgedPluginManager [v1.3.3](https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/tag/v1.3.3) 已适配这项更改
