### ISSUE TITLE
MPM运行错误

### ISSUE THREAD

**Issue by LSCube7** [Ivan-1F/MCDReforgedPluginManager#6]
```
Exception in thread MPMCache:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/MCDReforgedPluginManager-v2.0.0.mcdr/mcdreforged_plugin_manager/storage/cache.py", line 63, in cache
  File "plugins/MCDReforgedPluginManager-v2.0.0.mcdr/mcdreforged_plugin_manager/storage/cache.py", line 87, in load
  File "plugins/MCDReforgedPluginManager-v2.0.0.mcdr/mcdreforged_plugin_manager/storage/plugin.py", line 239, in create
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/utils/serializer.py", line 436, in deserialize
    return deserialize(data, cls, **kwargs)
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/utils/serializer.py", line 288, in deserialize
    set_result_attr(attr_name, deserialize(data[attr_name], attr_type, **kwargs))
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/utils/serializer.py", line 216, in deserialize
    mismatch(cls)
  File "/home/lscube/.local/lib/python3.9/site-packages/mcdreforged/utils/serializer.py", line 176, in mismatch
    raise TypeError('Mismatched input type: expected class {} but found data with class {}'.format(cls, type(data)))
TypeError: Mismatched input type: expected class <class 'str'> but found data with class <class 'NoneType'>

**Comment by Ivan-1F** [comment]
PluginCatalogue 对 schema 进行了大量修改，因此 mpm 需要重构插件的缓存

可以先使用 https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/7659453175 作为过渡方案，新版本将在重构完成后发布

需要对配置文件进行一些修改：

- 修改配置文件中的 `source` 字段，应是下载 meta 分支中 everything.json 的链接
- 移除 `MCDR/config/mcdreforged_plugin_manager` 中的 `PluginCatalogue-meta` 文件夹

最新的样例 config 文件位于 https://github.com/Ivan-1F/MCDReforgedPluginManager/blob/master/resources/default_config.yml

**Comment by BakaReimu** [comment]
> PluginCatalogue 对 schema 进行了大量修改，因此 mpm 需要重构插件的缓存
> 
> 可以先使用[https://github.com/Ivan-1F/MCDReorgedPluginManager/actions/runs/7659453175](https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/7659453175)作为过渡方案，新版本将在重构完成后发布
> 
> 需要修改对配置文件进行一些：
> 
> * 修改配置文件中的`source`字段，应是下载meta分支中 everything.json 的链接
> * 删除`MCDR/config/mcdreforged_plugin_manager`中的`PluginCatalogue-meta`文件夹
> 
> 最新的样例配置文件位于https://github.com/Ivan-1F/MCDReforgedPluginManager/blob/master/resources/default_config.yml

为什么插件在用utf8编码的everything.json就会报UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 4764: illegal multibyte sequence，重新通过gbk编码保存就能正常运行，但是自动更新下来的json文件默认是utf8的就很麻烦

**Comment by Ivan-1F** [comment]
> > PluginCatalogue 对 schema 进行了大量修改，因此 mpm 需要重构插件的缓存
> > 可以先使用[https://github.com/Ivan-1F/MCDReorgedPluginManager/actions/runs/7659453175](https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/7659453175)作为过渡方案，新版本将在重构完成后发布
> > 需要修改对配置文件进行一些：
> > 
> > * 修改配置文件中的`source`字段，应是下载meta分支中 everything.json 的链接
> > * 删除`MCDR/config/mcdreforged_plugin_manager`中的`PluginCatalogue-meta`文件夹
> > 
> > 最新的样例配置文件位于https://github.com/Ivan-1F/MCDReforgedPluginManager/blob/master/resources/default_config.yml
> 
> 为什么插件在用utf8编码的everything.json就会报UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 4764: illegal multibyte sequence，重新通过gbk编码保存就能正常运行，但是自动更新下来的json文件默认是utf8的就很麻烦

已于 a23dbd4 中修复：https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/9564721059

**Comment by Ivan-1F** [comment]
已发布 [v2.1.0](https://github.com/Ivan-1F/MCDReforgedPluginManager/releases/tag/v2.1.0)
