### ISSUE TITLE
插件在服务器启动时报错，并且无法刷新仓库

### ISSUE THREAD

**Issue by MC-Nirvana** [Ivan-1F/MCDReforgedPluginManager#7]
错误日志：
[MCDR] [13:51:10] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=mcdreforged_plugin_manager@2.1.0,priority=1000,callback=<function on_load at 0x7f2b8b721800>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mcdreforged/plugin/plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.11/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/[A][主体插件][插件管理]MCDReforgedPluginManager-v2.1.0.mcdr/mcdreforged_plugin_manager/entry.py", line 86, in on_load
    cache.load()
  File "plugins/[A][主体插件][插件管理]MCDReforgedPluginManager-v2.1.0.mcdr/mcdreforged_plugin_manager/storage/cache.py", line 77, in load
    for plugin in data['plugins'].values():
                  ~~~~^^^^^^^^^^^
KeyError: 'plugins'

服务端完整日志：
MCDReforged 2.12.3 is starting up
MCDReforged is open source, u can find it here: https://github.com/Fallen-Breath/MCDReforged
[MCDR] [13:51:09] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [13:51:09] [MainThread/INFO]: 编码 / 解码方式已设置为 utf8 / utf8
[MCDR] [13:51:09] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [13:51:09] [MainThread/INFO]: - plugins
[MCDR] [13:51:09] [MainThread/INFO]: 解析处理器已设置为 bukkit_handler
[MCDR] [13:51:09] [MainThread/INFO]: MCDReforged正于Python 3.11.9环境中运行
[MCDR] [13:51:09] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [13:51:09] [TaskExecutor/INFO]: 插件 mcdreforged_plugin_manager@2.1.0 已加载
[MCDR] [13:51:09] [TaskExecutor/INFO]: 插件 mcd_task@2.3.6+build.240207 已加载
[MCDR] [13:51:09] [TaskExecutor/INFO]: 插件 player_last_play@1.0.3 已加载
[MCDR] [13:51:09] [TaskExecutor/INFO]: 插件 online_player_api@1.0.0 已加载
[MCDR] [13:51:10] [MPMCacheClock/INFO] [mcdreforged_plugin_manager]: 插件库索引定时更新计时器启动，间隔 120 秒
[MCDR] [13:51:10] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=mcdreforged_plugin_manager@2.1.0,priority=1000,callback=<function on_load at 0x7f2b8b721800>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mcdreforged/plugin/plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.11/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/[A][主体插件][插件管理]MCDReforgedPluginManager-v2.1.0.mcdr/mcdreforged_plugin_manager/entry.py", line 86, in on_load
    cache.load()
  File "plugins/[A][主体插件][插件管理]MCDReforgedPluginManager-v2.1.0.mcdr/mcdreforged_plugin_manager/storage/cache.py", line 77, in load
    for plugin in data['plugins'].values():
                  ~~~~^^^^^^^^^^^
KeyError: 'plugins'
[MCDR] [13:51:10] [TaskExecutor/INFO] [mcd_task]: 配置文件已加载
[MCDR] [13:51:10] [TaskExecutor/INFO] [player_last_play]: 配置文件已加载
[MCDR] [13:51:10] [TaskExecutor/INFO] [player_last_play]: 配置文件已加载
[MCDR] [13:51:10] [TaskExecutor/INFO]: 共加载: 4 个插件; 已加载插件数: 6
[MCDR] [13:51:10] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xmx2048M -Xms2048M -javaagent:./authlib-injector.jar=https://littleskin.cn/api/yggdrasil -jar paper-1.20.6.jar nogui"
[MCDR] [13:51:10] [MainThread/INFO]: 服务端正在以 PID 4123 运行中
[Server] [authlib-injector] [INFO] Logging file: /root/MCDR-Server/paper/authlib-injector.log
[Server] [authlib-injector] [INFO] Version: 1.2.5
[Server] [authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
[Server] Starting org.bukkit.craftbukkit.Main
[Server] System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS) Host: Linux 6.8.12-amd64 (amd64)
[Server] Loading libraries, please wait...
[Server] [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[Server] WARN StatusConsoleListener Advanced terminal features are not available in this environment
[Server] [authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[Server] [authlib-injector] [INFO] Httpd is running on port 42231
[Server] [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[Server] [13:51:19 INFO]: Environment: Environment[sessionHost=http://127.0.0.1:42231/https/sessionserver.mojang.com, servicesHost=http://127.0.0.1:42231/https/api.minecraftservices.com, name=PROD]
[Server] [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo] with [Yggdrasil Public Key Transformer]
[Server] [13:51:21 INFO]: Loaded 1175 recipes
[Server] [13:51:21 INFO]: Loaded 1276 advancements
[Server] [13:51:21 INFO]: Starting minecraft server version 1.20.6
[Server] [13:51:21 WARN]: ****************************
[Server] [13:51:21 WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[Server] [13:51:21 WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[Server] [13:51:21 WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[Server] [13:51:21 WARN]: ****************************
[Server] [13:51:21 INFO]: Loading properties
[Server] [13:51:21 INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[Server] [13:51:22 INFO]: Server Ping Player Sample Count: 12
[Server] [13:51:22 INFO]: Using 4 threads for Netty based IO
[Server] [13:51:23 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
[Server]     We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
[Server]     For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[Server] [13:51:23 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[Server] [13:51:23 INFO]: Default game type: SURVIVAL
[Server] [13:51:23 INFO]: Generating keypair
[Server] [13:51:24 INFO]: Starting Minecraft server on *:25565
[Server] [13:51:24 INFO]: Using epoll channel type
[Server] [13:51:24 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[Server] [13:51:24 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[Server] [13:51:25 INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.0
[Server] [13:51:25 INFO]: [ViaVersion] ViaVersion 5.0.0 is now loaded. Registering protocol transformers and injecting...
[Server] [13:51:26 INFO]: [ViaVersion] Loading block connection mappings ...
[Server] [13:51:26 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[Server] [13:51:27 INFO]: [ViaBackwards] Loading translations...
[Server] [13:51:27 INFO]: [ViaBackwards] Registering protocols...
[Server] [13:51:28 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v5.0.0
[Server] [13:51:28 INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.4.0-SNAPSHOT
[Server] [13:51:30 INFO]: [Geyser-Spigot] Loading extensions...
[Server] [13:51:30 INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[Server] [13:51:30 INFO]: Server permissions file permissions.yml is empty, ignoring it
[Server] [13:51:30 INFO]: Preparing level "world"
[Server] [13:51:30 INFO]: Preparing start region for dimension minecraft:overworld
[Server] [13:51:32 INFO]: Time elapsed: 1737 ms
[Server] [13:51:32 INFO]: Preparing start region for dimension minecraft:the_nether
[Server] [13:51:32 INFO]: Time elapsed: 239 ms
[Server] [13:51:32 INFO]: Preparing start region for dimension minecraft:the_end
[Server] [13:51:32 INFO]: Time elapsed: 177 ms
[Server] [13:51:32 INFO]: [ViaVersion] Enabling ViaVersion v5.0.0
[Server] [13:51:32 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.5-1.20.6 (766)
[Server] [13:51:33 INFO]: [ViaBackwards] Enabling ViaBackwards v5.0.0
[Server] [13:51:33 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.4.0-SNAPSHOT
[Server] [13:51:33 INFO]: [Geyser-Spigot] ******************************************
[Server] [13:51:33 INFO]: [Geyser-Spigot]
[Server] [13:51:33 INFO]: [Geyser-Spigot] Loading Geyser version 2.4.0-SNAPSHOT (git-master-e7b1329)
[Server] [13:51:33 INFO]: [Geyser-Spigot]
[Server] [13:51:33 INFO]: [Geyser-Spigot] ******************************************
[Server] [authlib-injector] [INFO] Transformed [org.geysermc.geyser.skin.SkinProvider] with [Constant URL Transformer]
[Server] [13:51:42 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[Server] [13:51:42 INFO]: [Geyser-Spigot] Done (9.194s)! Run /geyser help for help!
[Server] [authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.SessionService] with [Constant URL Transformer]
[Server] [13:51:42 INFO]: Starting GS4 status listener
[Server] [13:51:42 INFO]: Thread Query Listener started
[Server] [13:51:42 INFO]: Starting remote control listener
[Server] [13:51:42 INFO]: Query running on 0.0.0.0:25565
[Server] [13:51:42 INFO]: Thread RCON Listener started
[Server] [13:51:42 INFO]: RCON running on 0.0.0.0:25575
[Server] [13:51:42 INFO]: Running delayed init tasks
[Server] [13:51:42 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[Server] [13:51:42 INFO]: Done (21.093s)! For help, type "help"
[Server] [13:51:42 INFO]: Thread RCON Client /127.0.0.1 started
[Server] [13:51:42 INFO]: Timings Reset
[MCDR] [13:51:42] [TaskExecutor/INFO]: rcon 密码错误，连接失败
[Server] [13:51:42 INFO]: Thread RCON Client /127.0.0.1 shutting down
[Server] [authlib-injector] [INFO] Transformed [net.minecraft.server.network.ServerLoginPacketListenerImpl] with [Username Character Check Transformer]
[Server] [authlib-injector] [INFO] Transformed [net.minecraft.server.network.ServerLoginPacketListenerImpl] with [Paper Username Check Transformer]
>

MCDReforged版本：2.12.3
插件版本：2.1.0
服务器版本：1.20.6
服务器核心：paper
系统环境：Debian Testing
Java环境：Java21
Python环境：Python3.11

**Comment by Ivan-1F** [comment]
请删除 `MCDR 根目录/config/mcdreforged_plugin_manager/everything.json`

然后试试这个版本：https://github.com/Ivan-1F/MCDReforgedPluginManager/actions/runs/9632126879

**Comment by MC-Nirvana** [comment]
简单测试了一下，确实没报错了。但不清楚是不是稳定没报错（因为这个报错也是概率性出现）
